### ISSUE TITLE
Helm Install - scripts/install_plugin.sh: Permission denied

### ISSUE THREAD

**Issue by n1kofr** [cvila84/helm-image#1]
Cannot install plugin using the command:

./helm plugin install https://github.com/cvila84/helm-image

I get the error:

> sh: scripts/install_plugin.sh: Permission denied
> Error: plugin install hook for "image" exited with error

Either need to add execution permission on the install_plugin.sh file or explicitly set "sh scripts/install_plugin.sh"

**Comment by cvila84** [comment]
closed by https://github.com/cvila84/helm-image/commit/f76f28b28346e4de3b55d36f7a4fbdada73449e5
