### ISSUE TITLE
Helm install - plugin installation fails because of version formatting

### ISSUE THREAD

**Issue by n1kofr** [cvila84/helm-image#2]
When running scripts/install_plugin.sh, we get the following errors:

> Downloading and installing image v"1.0.1"...
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> mv: cannot stat ‘releases/v"1.0.1"/helm-image’: No such file or directory
> mv: cannot stat ‘releases/v"1.0.1"/helm-image.exe’: No such file or directory
> mv: cannot stat ‘releases/v"1.0.1"/plugin.yaml’: No such file or directory
> mv: cannot stat ‘releases/v"1.0.1"/README.md’: No such file or directory
> mv: cannot stat ‘releases/v"1.0.1"/LICENSE’: No such file or directory

The plugin.yaml file should contains the version without double quote. Or the install_plugin.sh should remove the quote when fetching the binary and processing the installation.

**Comment by cvila84** [comment]
closed by https://github.com/cvila84/helm-image/commit/9965bfd614af6d294d96c57bc3e3de65c4d66ea5
