### ISSUE TITLE
Helm Install - ‘releases/v1.0.1/helm-image’: No such file or directory

### ISSUE THREAD

**Issue by n1kofr** [cvila84/helm-image#4]
The installation cannot find the binary file after extraction.
It is looking for  ‘releases/v1.0.1/helm-image’ instead of  ‘releases/v1.0.1/**bin/**helm-image’

> Downloading and installing image v1.0.1...
> mv: cannot stat ‘releases/v1.0.1/helm-image’: No such file or directory
> mv: cannot stat ‘releases/v1.0.1/helm-image.exe’: No such file or directory

**Comment by cvila84** [comment]
closed by https://github.com/cvila84/helm-image/commit/e54235fc17df38e3b22572aa051fea45639c05ca
